#!/usr/bin/env python3

import os
import sys
from collections import defaultdict
from decimal import Decimal

import pymysql
import psycopg2
from psycopg2 import sql


SOURCE_DATABASE = "ai-agent-station-study"
ALLOWED_EXISTING_TABLES = {"store_openai", "vector_store", "vector_store_openai"}
TYPE_MAP = {
    "bigint": "BIGINT",
    "int": "INTEGER",
    "tinyint": "SMALLINT",
    "text": "TEXT",
    "mediumtext": "TEXT",
    "longtext": "TEXT",
    "datetime": "TIMESTAMP",
    "timestamp": "TIMESTAMP",
}


def required_env(name):
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(f"Required environment variable is missing: {name}")
    return value


def source_connection():
    return pymysql.connect(
        host=required_env("MIGRATION_MYSQL_HOST"),
        port=int(os.environ.get("MIGRATION_MYSQL_PORT", "3306")),
        user=required_env("MIGRATION_MYSQL_USER"),
        password=required_env("MIGRATION_MYSQL_PASSWORD"),
        database=SOURCE_DATABASE,
        charset="utf8mb4",
        cursorclass=pymysql.cursors.DictCursor,
        autocommit=False,
    )


def target_connection():
    return psycopg2.connect(
        host=required_env("MIGRATION_POSTGRES_HOST"),
        port=int(os.environ.get("MIGRATION_POSTGRES_PORT", "5432")),
        user=required_env("MIGRATION_POSTGRES_USER"),
        password=required_env("MIGRATION_POSTGRES_PASSWORD"),
        dbname=required_env("MIGRATION_POSTGRES_DATABASE"),
    )


def postgres_type(column):
    data_type = column["DATA_TYPE"].lower()
    if data_type in ("varchar", "char"):
        return sql.SQL("{}({})").format(
            sql.SQL(data_type.upper()),
            sql.Literal(int(column["CHARACTER_MAXIMUM_LENGTH"])),
        )
    mapped = TYPE_MAP.get(data_type)
    if not mapped:
        raise RuntimeError(f"Unsupported MySQL type {data_type} on {column['TABLE_NAME']}.{column['COLUMN_NAME']}")
    return sql.SQL(mapped)


def default_clause(column):
    if "auto_increment" in (column["EXTRA"] or "").lower():
        return sql.SQL(" GENERATED BY DEFAULT AS IDENTITY")
    value = column["COLUMN_DEFAULT"]
    if value is None:
        return sql.SQL("")
    if isinstance(value, str) and value.upper().startswith("CURRENT_TIMESTAMP"):
        return sql.SQL(" DEFAULT CURRENT_TIMESTAMP")
    if column["DATA_TYPE"].lower() in {"bigint", "int", "tinyint"}:
        return sql.SQL(" DEFAULT {}").format(sql.Literal(int(value)))
    if isinstance(value, Decimal):
        return sql.SQL(" DEFAULT {}").format(sql.Literal(value))
    return sql.SQL(" DEFAULT {}").format(sql.Literal(value))


def load_metadata(source):
    with source.cursor() as cursor:
        cursor.execute(
            """
            SELECT TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, DATA_TYPE,
                   CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, COLUMN_DEFAULT, EXTRA
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = %s
            ORDER BY TABLE_NAME, ORDINAL_POSITION
            """,
            (SOURCE_DATABASE,),
        )
        columns = defaultdict(list)
        for row in cursor.fetchall():
            columns[row["TABLE_NAME"]].append(row)

        cursor.execute(
            """
            SELECT TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION
            FROM information_schema.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = %s AND CONSTRAINT_NAME = 'PRIMARY'
            ORDER BY TABLE_NAME, ORDINAL_POSITION
            """,
            (SOURCE_DATABASE,),
        )
        primary_keys = defaultdict(list)
        for row in cursor.fetchall():
            primary_keys[row["TABLE_NAME"]].append(row["COLUMN_NAME"])

        cursor.execute(
            """
            SELECT TABLE_NAME, INDEX_NAME, NON_UNIQUE, COLUMN_NAME, SEQ_IN_INDEX
            FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = %s AND INDEX_NAME <> 'PRIMARY'
            ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX
            """,
            (SOURCE_DATABASE,),
        )
        indexes = defaultdict(lambda: defaultdict(lambda: {"unique": False, "columns": []}))
        for row in cursor.fetchall():
            item = indexes[row["TABLE_NAME"]][row["INDEX_NAME"]]
            item["unique"] = row["NON_UNIQUE"] == 0
            item["columns"].append(row["COLUMN_NAME"])
    return columns, primary_keys, indexes


def check_target(target, source_tables):
    with target.cursor() as cursor:
        cursor.execute("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
        existing = {row[0] for row in cursor.fetchall()}
    unexpected = existing - ALLOWED_EXISTING_TABLES
    collisions = existing & set(source_tables)
    if unexpected or collisions:
        raise RuntimeError(
            f"Target database contains unexpected or colliding tables: {sorted(unexpected | collisions)}"
        )


def create_tables(target, columns, primary_keys):
    with target.cursor() as cursor:
        for table_name, table_columns in columns.items():
            definitions = []
            for column in table_columns:
                definition = sql.SQL("{} {}").format(
                    sql.Identifier(column["COLUMN_NAME"]),
                    postgres_type(column),
                )
                definition += default_clause(column)
                if column["IS_NULLABLE"] == "NO":
                    definition += sql.SQL(" NOT NULL")
                definitions.append(definition)
            pk = primary_keys.get(table_name)
            if pk:
                definitions.append(
                    sql.SQL("PRIMARY KEY ({})").format(
                        sql.SQL(", ").join(map(sql.Identifier, pk))
                    )
                )
            cursor.execute(
                sql.SQL("CREATE TABLE {} ({})").format(
                    sql.Identifier(table_name),
                    sql.SQL(", ").join(definitions),
                )
            )


def copy_and_verify(source, target, columns, primary_keys):
    copied = {}
    for table_name, table_columns in columns.items():
        names = [item["COLUMN_NAME"] for item in table_columns]
        order_by = primary_keys.get(table_name) or names
        select_query = "SELECT {} FROM `{}` ORDER BY {}".format(
            ", ".join(f"`{name}`" for name in names),
            table_name,
            ", ".join(f"`{name}`" for name in order_by),
        )
        with source.cursor() as source_cursor:
            source_cursor.execute(select_query)
            source_rows = [tuple(row[name] for name in names) for row in source_cursor.fetchall()]

        if source_rows:
            insert_query = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
                sql.Identifier(table_name),
                sql.SQL(", ").join(map(sql.Identifier, names)),
                sql.SQL(", ").join(sql.Placeholder() for _ in names),
            )
            with target.cursor() as target_cursor:
                target_cursor.executemany(insert_query, source_rows)

        with target.cursor() as target_cursor:
            target_cursor.execute(
                sql.SQL("SELECT {} FROM {} ORDER BY {}").format(
                    sql.SQL(", ").join(map(sql.Identifier, names)),
                    sql.Identifier(table_name),
                    sql.SQL(", ").join(map(sql.Identifier, order_by)),
                )
            )
            target_rows = target_cursor.fetchall()

        if source_rows != target_rows:
            raise RuntimeError(f"Data verification failed for {table_name}")
        copied[table_name] = len(source_rows)
    return copied


def create_indexes_and_reset_sequences(target, columns, indexes):
    with target.cursor() as cursor:
        for table_name, table_indexes in indexes.items():
            for ordinal, (_, index) in enumerate(sorted(table_indexes.items()), start=1):
                prefix = "uq" if index["unique"] else "ix"
                index_name = f"{prefix}_{table_name}_{ordinal}"[:63]
                cursor.execute(
                    sql.SQL("CREATE {} INDEX {} ON {} ({})").format(
                        sql.SQL("UNIQUE") if index["unique"] else sql.SQL(""),
                        sql.Identifier(index_name),
                        sql.Identifier(table_name),
                        sql.SQL(", ").join(map(sql.Identifier, index["columns"])),
                    )
                )

        for table_name, table_columns in columns.items():
            for column in table_columns:
                if "auto_increment" not in (column["EXTRA"] or "").lower():
                    continue
                column_name = column["COLUMN_NAME"]
                cursor.execute(
                    "SELECT setval(pg_get_serial_sequence(%s, %s), "
                    "COALESCE((SELECT MAX({}) FROM {}), 1), "
                    "EXISTS (SELECT 1 FROM {}))".format(
                        sql.Identifier(column_name).as_string(target),
                        sql.Identifier(table_name).as_string(target),
                        sql.Identifier(table_name).as_string(target),
                    ),
                    (table_name, column_name),
                )


def main():
    source = source_connection()
    target = target_connection()
    try:
        columns, primary_keys, indexes = load_metadata(source)
        if len(columns) != 14:
            raise RuntimeError(f"Expected 14 source tables, found {len(columns)}")
        check_target(target, columns.keys())
        create_tables(target, columns, primary_keys)
        copied = copy_and_verify(source, target, columns, primary_keys)
        create_indexes_and_reset_sequences(target, columns, indexes)
        target.commit()
        for table_name in sorted(copied):
            print(f"{table_name}|{copied[table_name]}|verified")
        print(f"migration_verified_tables={len(copied)} rows={sum(copied.values())}")
    except Exception:
        target.rollback()
        raise
    finally:
        source.close()
        target.close()


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"migration_failed={type(error).__name__}: {error}", file=sys.stderr)
        sys.exit(1)
